### PR TITLE
Correct location of William T Riker's birthplace.

### PR DESCRIPTION
**Pull request by seanmdick**
@mdimas @mertonium @erikogan

### CODE REVIEW

**Comment by quaelin** [comment]
LGTM, verified at http://memory-beta.wikia.com/wiki/William_T._Riker

**Comment by mertonium** [comment]
As long as we assume he signed from his birthplace, as opposed to a Starfleet Academy dorm in SF, LGTM.

**Comment by quaelin** [comment]
Yeah that occurred to me too.  Based on the sign date, he wouldn't even be born yet so we are best to assume that he did a slingshot maneuver around the sun in order to travel back to the year 2012.  Question then becomes, would he have wanted to visit the eventual location of Starfleet Academy, or his ancestors in AK.  The latter seems more likely to me.

**Comment by seanmdick** [comment]
@mertonium makes a good point. SF is widely known as Starfleet HQ.

**Comment by seanmdick** [comment]
:eyeglasses: :arrow_up: :nose:

**Pull request merged**
